  language: python
  python:
    - "3.6"
  
  branches:
    only:
      - "master"
  
  env:
    global:
      - PIPENV_VENV_IN_PROJECT=1
      - PIPENV_IGNORE_VIRTUALENVS=1

  install:
    - pip install pipenv
    - pipenv sync --dev --three

  script:
    - pipenv run python -m flake8

  cache: pip

  notifications:
    email:
      on_success: never
      on_failure: never
